version: '3.7'

services:
  palantir-consul-1:
    image: consul:1.9.3
    container_name: palantir-consul-1
    restart: always
    volumes:
      - ./server1.json:/consul/config/server1.json:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    command: 'agent -bootstrap-expect=3'

    palantir-consul-2:
    image: consul:1.9.3
    container_name: palantir-consul-2
    restart: always
    volumes:
      - ./server2.json:/consul/config/server2.json:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: 'agent -bootstrap-expect=3'

    palantir-consul-3:
    image: consul:1.9.3
    container_name: palantir-consul-3
    restart: always
    volumes:
      - ./server3.json:/consul/config/server3.json:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: 'agent -bootstrap-expect=3'

  consul-client:
    image: consul:1.9.3
    container_name: consul-client
    restart: always
    volumes:
      - ./client.json:/consul/config/client.json:ro
      - ./certs/consul-agent-ca.pem:/consul/config/certs/consul-agent-ca.pem:ro
    networks:
      - consul
    command: 'agent'

networks:
  consul:
    driver: bridge
